### ISSUE TITLE
Price prediction date

### ISSUE THREAD

**Issue by tjorim** [myTselection/Carbu_com#36]
I assume this is a bug since the attributes contain both a 'last update' and 'date' but they're the same. If would be more useful if the latter would indicate when the price will probably change.

![Screenshot_20231101-222455.png](https://github.com/myTselection/Carbu_com/assets/1294876/48347517-d776-496a-8d21-d120b2e9d5d9)

**Comment by myTselection** [comment]
fixed in 8.1.0

**Comment by tjorim** [comment]
Seems like it's not fixed yet. I now see this:
<img width="423" alt="image" src="https://github.com/myTselection/Carbu_com/assets/1294876/430576c7-b4dc-4ba8-85ca-5f051f452e31">
The date is in the past while the drop will happen in "+1" (business day, so tomorrow).
Expected date would be 08/01/2024.

**Comment by myTselection** [comment]
fixed, using the last date shown in graph of https://carbu.com//belgie/voorspellingen + 5 days added.

**Comment by tjorim** [comment]
Where is the + 5 days coming from? Now it tells me 10/01/2024 while the graph shows 08/01/2024:
![image](https://github.com/myTselection/Carbu_com/assets/1294876/57875ad8-bdf6-446a-9740-c4cc390377f0)

**Comment by myTselection** [comment]
The graph goes up to +5 and I use the latest value to calculate the difference with current value...

**Comment by tjorim** [comment]
Ah got it, I was hoping to get a 'countdown' timer to when price will go down or up.
