### ISSUE TITLE
"Wrong" local station

### ISSUE THREAD

**Issue by GiorgioAresu** [myTselection/Carbu_com#77]
Hi, thanks for this!
I'm trying to set this up for IT, but I'm facing an issue.
Contrary to my understanding of how it should work, the sensor ending with `_price` seems to just show the closest (as the crow flies) station. I'm still ok with this, as it's maybe just a limitation of the IT APIs, seeing distance is not supported in that sensor. I can still use it as closest (incidentally it's also the one that's usually the cheapest) vs 5km vs 10km. The issue with my specific case is that I have like 2 within a VERY small radius <200m, and the sensor is showing the wrong one. I believe this is due to the precision of the coordinates returned by the api.
If I use the event, I have the same issue, but I can set max_distance: 1 (or even smaller than that) and get the correct one. Is there a way I can do something similar with the sensor without doing workarounds with manually calling the events?

**Comment by myTselection** [comment]
could you give some example queries used (postal code, location)? as it's based on sorting by closest and cheapest.

the _price sensor indeed should aways provide the price of the cheapest station at the defined location/postalcode.
the _5km and _10km sensors provide the lowest price in a area around the defined base location/postalcode

**Comment by GiorgioAresu** [comment]
Can I send it to you privately rather than here?

**Comment by myTselection** [comment]
sure: mytselection[at]gmail.com

**Comment by myTselection** [comment]
hi, thanks, I received your input on jan 6th, but still need to look into it.

**Comment by myTselection** [comment]
Hi, I'm looking into this.
You are aware there is an option to select an individual gas station instead of having a sensor pointing the the cheapest gas station in the selected city?
In the second set of the setup of a new Carbu integration, the option to 'select an individual station' needs to be set. This should allow you to see the prices only of that specific station.

![Image](https://github.com/user-attachments/assets/61f1e355-ee27-453c-b7b7-31db05fd7db7)

I'm still checking why setting a different distance still seems to find a cheaper station though.

**Comment by myTselection** [comment]
if the max distance is 0, we expect the first result to be the closest and cheapest for the given location. For most countries this works well, yet for IT the results returned doesn't seem to be sorted. I will now apply a fix to search for the cheapest for the local sensor.

**Comment by GiorgioAresu** [comment]
Hi, thanks, I think I've seen that in the docs but my brain just ignored it, I'm happy to use that as that would be my default go-to station anyway

**Comment by myTselection** [comment]
should be fixed now for IT in R11.3.2 to make sure the local sensor is also the cheapest in local environment.
Thanks for reporting this!

**Comment by GiorgioAresu** [comment]
I just upgraded but it's still showing inaccurate data. I can send screenshots but basically comparing to the prezzibenzina app, I see for diesel there are 2 (one which is the closest and one in the next town) that are cheapest with the same price, and carbu is showing the farthest of the 2 for all 3 sensors. For super95 the price has the same situation and same 2 stations, but carbu is showing the right price but with a station name that's neither of the 2. Looking at the _price sensors, they both went down after the update, which means it's working, but I don´t think it's possible to check the history of the attributes? Is it possible to downgrade without reconfiguring just to check what the results were before the update?
